## Carbon Storage, Tree growth and Caron Sequestration Rate for NYC Street Trees 

With NYC street tree species and dbh measurements, carbon storage for each tree can be calculated based on allometric equations. Half of he  above-ground biomass (AGB) is carbon stored by trees. AGB = wood density * woody volume. Wood volume can be estimated as a function of dbh (or dbh and tree height) using allometric equations. Urban tree allometric equations (woody volume and wood density) can be found [here](https://www.fs.usda.gov/rds/archive/Catalog/RDS-2016-0005).

# Table of Contents

1. [Import libraries](#1)<br>
2. [Read data and preliminary check](#2)<br>
3. [Clean the data](#3)<br>
4. [Calculate the carbon storage and carbon sequestration ](#4)<br>    

</div>
<hr>

## Import libraries   <a id=1></a>

In [ ]:
import pandas as pd
import pdb
import numpy as np

#For interactive matplotlib sessions
%matplotlib inline 
import matplotlib.pyplot as plt
pd.__version__

## Read data and preliminary check  <a id=2></a>

In [ ]:

# You can read 2015 tree census data using pd.read_csv 
tree2015 = pd.read_csv('http://www.geography.hunter.cuny.edu/~wenge/EDS2023F/data/NYCtree/2015_Street_Tree_Census.csv')
tree2005 = pd.read_csv('http://www.geography.hunter.cuny.edu/~wenge/EDS2023F/data/NYCtree/2005_Street_Tree_Census.csv')                       
tree1995 = pd.read_csv('http://www.geography.hunter.cuny.edu/~wenge/EDS2023F/data/NYCtree/1995_Street_Tree_Census.csv')

In [12]:
tree2015.head()

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
0,180683,348711,08/27/2015,3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,4073900,New York,40.723092,-73.844215,1027431.148,202756.7687,29.0,739.0,4052307.0,4.022210e+09
1,200540,315986,09/03/2015,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,...,4097300,New York,40.794111,-73.818679,1034455.701,228644.8374,19.0,973.0,4101931.0,4.044750e+09
2,204026,218365,09/05/2015,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.717581,-73.936608,1001822.831,200716.8913,34.0,449.0,3338310.0,3.028870e+09
3,204337,217969,09/05/2015,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.713537,-73.934456,1002420.358,199244.2531,34.0,449.0,3338342.0,3.029250e+09
4,189565,223043,08/30/2015,21,0,OnCurb,Alive,Good,Tilia americana,American linden,...,3016500,New York,40.666778,-73.975979,990913.775,182202.4260,39.0,165.0,3025654.0,3.010850e+09

In [9]:
tree1995.head()

,RecordId,Address,House_Number,Street,Postcode_Original,Community Board_Original,Site,Species,Diameter,Condition,...,CensusTract_2010,CensusBlock_2010,NTA_2010,SegmentID,Spc_Common,Spc_Latin,Location,Council District,BIN,BBL
0,1,245 E 17 ST,245.0,E 17 ST,10003,106,Front,PLAC,8,Unknown,...,48.0,2000.0,MN21,33134,LONDON PLANETREE,PLATANUS ACERIFOLIA,"(40.734551, -73.984235)",2.0,1019566.0,1.008980e+09
1,2,80 N MOORE ST,80.0,N MOORE ST,10013,101,Side,ACPL,7,Good,...,39.0,2001.0,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)",1.0,1083157.0,1.001420e+09
2,3,80 N MOORE ST,80.0,N MOORE ST,10013,101,Side,ACPL,6,Good,...,39.0,2001.0,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)",1.0,1083157.0,1.001420e+09
3,4,80 N MOORE ST,80.0,N MOORE ST,10013,101,Side,ACPL,7,Excellent,...,39.0,2001.0,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)",1.0,1083157.0,1.001420e+09
4,5,80 N MOORE ST,80.0,N MOORE ST,10013,101,Side,ACPL,6,Good,...,39.0,2001.0,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)",1.0,1083157.0,1.001420e+09

In [10]:
tree2005.head()

,OBJECTID,cen_year,tree_dbh,address,tree_loc,pit_type,soil_lvl,status,spc_latin,spc_common,...,state,latitude,longitude,x_sp,y_sp,objectid_1,census tract,bin,bbl,Location 1
0,592373,2005,6,1139 57 STREET,Front,Sidewalk Pit,Level,Good,PYRUS CALLERYANA,"PEAR, CALLERY",...,New York,40.632653,-74.000245,984182,169769,0,216.0,3140038.0,3.056890e+09,"(40.63265321, -74.00024499)"
1,592374,2005,6,2220 BERGEN AVENUE,Across,Sidewalk Pit,Level,Good,PLATANUS ACERIFOLIA,LONDON PLANETREE,...,New York,40.620084,-73.901453,1011608,165205,1,706.0,3238037.0,3.084440e+09,"(40.62008375, -73.9014528)"
2,592375,2005,13,2360 BERGEN AVENUE,Front,Continuous Pit,Level,Good,ACER PLATANOIDES CRIMSON KING,"MAPLE, NORWAY-CR KNG",...,New York,40.617996,-73.899111,1012259,164445,2,706.0,3238299.0,3.084530e+09,"(40.61799567, -73.89911096)"
3,592376,2005,13,2254 BERGEN AVENUE,Across,Sidewalk Pit,Level,Good,PLATANUS ACERIFOLIA,LONDON PLANETREE,...,New York,40.619694,-73.901003,1011733,165063,3,706.0,3238045.0,3.084440e+09,"(40.6196936, -73.90100311)"
4,592377,2005,15,2332 BERGEN AVENUE,Across,Sidewalk Pit,Level,Good,PLATANUS ACERIFOLIA,LONDON PLANETREE,...,New York,40.618323,-73.899467,1012160,164564,4,706.0,3238294.0,3.084530e+09,"(40.61832261, -73.89946707)"

In [6]:
tree2015.columns

Index(['tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam',
       'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward',
       'guards', 'sidewalk', 'user_type', 'problems', 'root_stone',
       'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other',
       'brch_light', 'brch_shoe', 'brch_other', 'address', 'postcode',
       'zip_city', 'community board', 'borocode', 'borough', 'cncldist',
       'st_assem', 'st_senate', 'nta', 'nta_name', 'boro_ct', 'state',
       'latitude', 'longitude', 'x_sp', 'y_sp', 'council district',
       'census tract', 'bin', 'bbl'],
      dtype='object')

In [14]:
tree2015.shape

(683788, 45)

In [10]:
# Find the most dominant species and tree counts
treecount2015 = tree2015.groupby('spc_latin').size()
treecount2015_sorted = treecount2015.sort_values(ascending=False)
treecount2015_sorted[0:10]

spc_latin
Platanus x acerifolia                 87014
Gleditsia triacanthos var. inermis    64264
Pyrus calleryana                      58931
Quercus palustris                     53185
Acer platanoides                      34189
Tilia cordata                         29742
Prunus                                29279
Zelkova serrata                       29258
Ginkgo biloba                         21024
Styphnolobium japonicum               19338
dtype: int64

In [20]:
# Find the most dominant species and tree counts
treecount2015 = tree2015.groupby('spc_common').size()
treecount2015_sorted = treecount2015.sort_values(ascending=False)
treecount2015_sorted[0:10]

spc_common
London planetree     87014
honeylocust          64264
Callery pear         58931
pin oak              53185
Norway maple         34189
littleleaf linden    29742
cherry               29279
Japanese zelkova     29258
ginkgo               21024
Sophora              19338
dtype: int64

In [17]:
# Select big trees 
bigtree2015 = tree2015.loc[tree2015['tree_dbh'] > 10]
bigtree2015.shape

(307728, 45)

In [18]:
# Find the most dominant species and tree counts
bigtreecount2015 = bigtree2015.groupby('spc_common').size()
bigtreecount2015_sorted = bigtreecount2015.sort_values(ascending=False)
bigtreecount2015_sorted[0:10]

spc_common
London planetree     77363
pin oak              36817
honeylocust          31416
Norway maple         25435
Callery pear         18527
littleleaf linden    12577
green ash            11833
silver maple         10452
Japanese zelkova      7764
red maple             7603
dtype: int64

In [19]:
# Find the most dominant species and tree counts
bigtreecount2015 = bigtree2015.groupby('spc_latin').size()
bigtreecount2015_sorted = bigtreecount2015.sort_values(ascending=False)
bigtreecount2015_sorted[0:10]

spc_latin
Platanus x acerifolia                 77363
Quercus palustris                     36817
Gleditsia triacanthos var. inermis    31416
Acer platanoides                      25435
Pyrus calleryana                      18527
Tilia cordata                         12577
Fraxinus pennsylvanica                11833
Acer saccharinum                      10452
Zelkova serrata                        7764
Acer rubrum                            7603
dtype: int64

Allometric equations 
London planetree:

## Clean the data   <a id=3></a>
- make sure three year data have same variable names (particularly the same species names and borough  names etc.)

## Calculate the carbon storage and carbon sequestration <a id=4></a>

- Implement the allometric equations for top dominant tree species 
- Calculte the carbon storage for top dominant species using dbh and tree species information 
- Compare difference between 1995, 2005 and 2015